project_id = "fkarwrqwwnssnfioiaau"

[functions.send-approval-email]
verify_jwt = false

[functions.notify-admin-message]
verify_jwt = false

[functions.test-email]
verify_jwt = false

[functions.notify-new-registration]
verify_jwt = false

[functions.send-chat-notification]
verify_jwt = false

[functions.delete-own-account]
verify_jwt = false

[functions.moderate-content]
verify_jwt = false

[functions.send-marketing-email]
verify_jwt = false

[functions.send-partner-reminder]
verify_jwt = false